package com.revature.pojo;

public class Offer {
	private Integer offerId;
	private Integer carId;
	private Integer userId;
	private Double amount;
	private boolean accepted;
	private boolean removed;
	public Integer getOfferId() {
		return offerId;
	}
	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}
	public Integer getCarId() {
		return carId;
	}
	public void setCarId(Integer carId) {
		this.carId = carId;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public Double getAmount() {
		return amount;
	}
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	public boolean isAccepted() {
		return accepted;
	}
	public void setAccepted(boolean accepted) {
		this.accepted = accepted;
	}
	public boolean isRemoved() {
		return removed;
	}
	public void setRemoved(boolean removed) {
		this.removed = removed;
	}
	
	//Add offer constructor, offerId generated by DB
	public Offer(Integer carId, Integer userId, Double amount) {
		super();
		this.carId = carId;
		this.userId = userId;
		this.amount = amount;
		this.accepted = false;
		this.removed = false;
	}
	
	//Read offer constructor
	public Offer(Integer offerId, Double amount, boolean accepted, boolean removed, Integer userId, Integer carId) {
		super();
		this.offerId = offerId;
		this.amount = amount;
		this.accepted = accepted;
		this.removed = removed;
		this.carId = carId;
		this.userId = userId;
	}
	
	
	
}
